### ISSUE TITLE
No chat GUI with my modpack

### ISSUE THREAD

**Issue by ManicQuinn** [XKaguya/SpectatorChat#1]
This is my modlist on R2Modman: 018cfc01-f814-f283-5409-1a27ff34edba

**Comment by XKaguya** [comment]
> This is my modlist on R2Modman: 018cfc01-f814-f283-5409-1a27ff34edba

I'll fix when i'm free. Thank you for the information.

The new version will also include the feature about to chat with live player.

**Comment by XKaguya** [comment]
> This is my modlist on R2Modman: 018cfc01-f814-f283-5409-1a27ff34edba

Fixed now, Please wait for like 10m for thunderstore update the list 😉

**Comment by XKaguya** [comment]
> This is my modlist on R2Modman: 018cfc01-f814-f283-5409-1a27ff34edba

Test and got a bug will broken the game. Will fix asap.

**Comment by XKaguya** [comment]
> This is my modlist on R2Modman: 018cfc01-f814-f283-5409-1a27ff34edba

Fixed

**Comment by ManicQuinn** [comment]
> > This is my modlist on R2Modman: 018cfc01-f814-f283-5409-1a27ff34edba
> 
> Fixed

Thank you
