### ISSUE TITLE
Script cannot be instantiated

### ISSUE THREAD

**Issue by Ferrenom** [XKaguya/SpectatorChat#2]
With the new version 1.0.7 the plugin cannot be instantiated and console shows it as 1.0.6 instead of 1.0.7, i tried to reinstall the mod with cache disabled and still is shown as 1.0.6 . 

![image_2024-01-13_182748746](https://github.com/XKaguya/SpectatorChat/assets/36527178/dee7ee58-d191-44e7-b9d1-b453d7aa49b9)

**Comment by Ferrenom** [comment]
here is the profile code if you need it: 018d0373-e78b-07d6-d614-c498a3f88096

**Comment by XKaguya** [comment]
> With the new version 1.0.7 the plugin cannot be instantiated and console shows it as 1.0.6 instead of 1.0.7, i tried to reinstall the mod with cache disabled and still is shown as 1.0.6 .
> 
> ![image_2024-01-13_182748746](https://private-user-images.githubusercontent.com/36527178/296500103-dee7ee58-d191-44e7-b9d1-b453d7aa49b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNjAyOTEsIm5iZiI6MTcwNTE1OTk5MSwicGF0aCI6Ii8zNjUyNzE3OC8yOTY1MDAxMDMtZGVlN2VlNTgtZDE5MS00NGU3LWI5ZDEtYjQ1M2Q3YWE0OWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDE1MzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NGEzYmI0ZmFmYzVkZDAyMTFmNWFjMGE2ZmUzZGQ5ODEyNGMyODRlNTFjYzI2OTc0ODkxZGE1OWYwMDVmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AlyfW7AZTQA_ti0nEA6DM3KkJ_1Z_syoW1xDZx0fwdc)

That is never seen for me. I'll look about it asap.

Version problem is maybe becaused i forget to change the version number lol. It doesnt matter anyway.

**Comment by Ferrenom** [comment]
Thanks, and I do have to mention that i'm using the r2modman instead of thunderstore if that helps as well.

**Comment by XKaguya** [comment]
> Thanks, and I do have to mention that i'm using the r2modman instead of thunderstore if that helps as well.

I'm using r2modman also. I think it has no any problem with both mod manager.

**Comment by Ferrenom** [comment]
> > Thanks, and I do have to mention that i'm using the r2modman instead of thunderstore if that helps as well.
> 
> I'm using r2modman also. I think it has no any problem with both mod manager.

Oh alright then I'll just have to wait for the update then, thanks

**Comment by XKaguya** [comment]
> > > Thanks, and I do have to mention that i'm using the r2modman instead of thunderstore if that helps as well.
> > 
> > 
> > I'm using r2modman also. I think it has no any problem with both mod manager.
> 
> Oh alright then I'll just have to wait for the update then, thanks

Sorry for delay. Issue is now fixed. Please wait till thunder update the mod list 😉

**Comment by Ferrenom** [comment]
Thanks I'll have to wait for that then close the thread after, or just manual install it for now to check it out

**Comment by Ferrenom** [comment]
Tested and everything does seems to be working now, thanks once again for the fix!

**Comment by XKaguya** [comment]
> Tested and everything does seems to be working now, thanks once again for the fix!

Np, feel free to submit issue when you met bugs :)
